export const FETCH_QUIZLIST_START = "FETCH_QUIZLIST_START";
export const FETCH_QUIZLIST_END = "FETCH_QUIZLIST_END";
export const FETCH_QUIZLIST_ERROR = "FETCH_QUIZLIST_ERROR";

export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
export const QUIZ_END = "QUIZ_END";
export const FETCH_QUIZ_SET_STATE = "FETCH_QUIZ_SET_STATE";
export const FETCH_QUIZ_ERROR = "FETCH_QUIZ_ERROR";
export const QUIZ_REPEAT = "QUIZ_REPEAT";
export const FETCH_QUIZ_START = "FETCH_QUIZ_START";

export const FORM_ELEMENTS_SET_STATE = "FORM_ELEMENTS_SET_STATE";
export const ADD_ANSWER_SET_STATE = "ADD_ANSWER_SET_STATE";
export const SELECT_SET_STATE = "SELECT_SET_STATE";
export const ADD_QUIZ_SET_STATE = "ADD_QUIZ_SET_STATE";
export const DELETE_SET_STATE = "DELETE_SET_STATE";
